apiVersion: v1
kind: ConfigMap
metadata:
  name: payops-config
  namespace: {{ .Values.global.namespace }}
data:
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  DB_USER: {{ .Values.config.dbUser | quote }}
  DB_SSL: {{ .Values.config.dbSsl | quote }}
  JWT_EXPIRY: {{ .Values.config.jwtExpiry | quote }}
  RABBITMQ_URL: {{ .Values.config.rabbitmqUrl | quote }}
  AUTH_SERVICE_URL: "http://{{ .Values.services.authService.name }}:{{ .Values.services.authService.port }}"
  TRANSACTION_SERVICE_URL: "http://{{ .Values.services.transactionService.name }}:{{ .Values.services.transactionService.port }}"
  NOTIFICATION_SERVICE_URL: "http://{{ .Values.services.notificationService.name }}:{{ .Values.services.notificationService.port }}"
