apiVersion: v1
kind: ConfigMap
metadata:
  name: payops-config
  namespace: payops-dev
data:
  DB_HOST: "payopsdevpg.postgres.database.azure.com"
  DB_PORT: "5432"
  DB_NAME: "payops"
  DB_USER: "payopsadmin"
  DB_SSL: "true"
  JWT_EXPIRY: "1h"
  RABBITMQ_URL: "amqp://payops:payops123@rabbitmq:5672"
  AUTH_SERVICE_URL: "http://auth-service:8081"
  TRANSACTION_SERVICE_URL: "http://transaction-service:8082"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8083"
