apiVersion: v1
kind: Secret
metadata:
  name: payops-secrets
  namespace: payops
type: Opaque
stringData:
  POSTGRES_PASSWORD: "change-me"
  RABBITMQ_DEFAULT_PASS: "change-me"
  JWT_SECRET: "change-me"
